### ISSUE TITLE
allow to specify an environment for the tested script when recording protocols

### ISSUE THREAD

**Issue by soenkehahn** [Originate/check-protocols#147]
There's two options for the UI for this:

1. Have a cli flag, e.g. `--env FOO=BAR --env BAZ=HUHU`

2. Have some mechanism to put holes into protocols, e.g.:

``` yaml
env:
  FOO: BAR
  BAZ: HUHU
protocols:
  - protocol:
      - _
```

Here, the underscore is used to mean that `check-protocols` should fill in the rest.
