### ISSUE TITLE
add description to a protocol

### ISSUE THREAD

**Issue by soenkehahn** [Originate/check-protocols#152]
``` yaml
protocols:
  - description: does this nice thing
    protocol: ...
  - description: does this other nice thing
    protocol: ...
```

should result in

```
myscript.sh
does this nice thing
does this other nice thing
All tests passed.
```

Or something like that.
