### ISSUE TITLE
support pipes when recording

### ISSUE THREAD

**Issue by soenkehahn** [Originate/check-protocols#157]
For example this doesn't work:
``` bash
#!/usr/bin/env bash
ls | sed s/foo/bar/g
```
``` yaml
unmockedCommands:
  - sed
protocols:
  - protocol:
      - _
```
