### ISSUE TITLE
format errors better

### ISSUE THREAD

**Issue by soenkehahn** [Originate/check-protocols#41]
When the tool fails the error output looks like e.g. this:
```
Error: StringError("expected: single yaml document, got: [Hash({String(\"arguments\"): String(\"test-file\"), String(\"protocol\"): Array([String(\"/bin/chmod +r test-file.txt\"), Hash({String(\"command\"): String(\"/bin/cat test-file.txt\"), String(\"stdout\"): String(\"should be deleted\")}), String(\"/bin/rm test-file.txt\")])}), Hash({String(\"arguments\"): String(\"foo\")})]")
```
It should instead print out the string.

**Comment by matthandlersux** [comment]
also YAML parse errors look like

```
Error: ScanError { mark: Marker { index: 140, line: 6, col: 0 }, info: "while parsing a block mapping, did not find expected key" }
```

and it's not clear if this is a problem with my protocol file itself, or the test that is being run

**Comment by soenkehahn** [comment]
@matthandlersux: Do you still have the yaml file that produced this error?

**Comment by matthandlersux** [comment]
```yaml
arguments: test-file
protocol:
  - command: /bin/chmod +r test-file.txt
  - command: /bin/cat test-file.txt
    stdout: "should be deleted"
- /bin/rm test-file.txt
```
i think i just had a weird paste from your example file
