### ISSUE TITLE
document available YAML keys

### ISSUE THREAD

**Issue by matthandlersux** [Originate/check-protocols#44]
it would be nice to have a section in the readme with a running list of "keys you can use in your test files". for example, it might start out with just:

```yaml
arguments: string | string[] # ex: --some-flag
protocol: # command[]
  - command: string # ex: - /bin/chmod +r test-file.txt
```

how would one specify env variables via the protocol?
