### ISSUE TITLE
allow to specify environment variables for the script

### ISSUE THREAD

**Issue by soenkehahn** [Originate/check-protocols#49]
``` yaml
env:
  TR_APP_VERSION: 0.1.0
arguments: --some-flag
protocol:
  - bla
```
