### ISSUE TITLE
ability to test commands that include arguments with spaces

### ISSUE THREAD

**Issue by astampoulis** [Originate/check-protocols#67]
For example, ability to specify a protocol like:
```yaml
- executable: /usr/bin/g it
  arguments:
    - commit
    - -m
    - re encrypted
```
for:
`"g it" commit -m "re ecnrypted"`
