### ISSUE TITLE
No way to mock file/folder existence 

### ISSUE THREAD

**Issue by matthandlersux** [Originate/check-protocols#72]
i have a ruby script that checks for files/folders (ex: `if File.exists?("/usr/local/bin/unrar")`. i don't believe that this call is intercepted by check-protocols, and i'm not sure if it's possible to intercept it. this would likely not be a problem if i could run the tool on my machine, but since it is running within docker, the files/folders don't exist.

if it's not possible to intercept these types of calls, i would ideally be able to create a folder tree as part of my protocol. off the top of my head, something like the following could work:
```yaml
filetree:
  usr: 
    local:
      bin: unrar
protocol:
  ...
```
or
```yaml
filetree:
  - /usr/local/bin/unrar
protocol:
  ...
```

in my particular case, i check for the existence of executables, directories, and regular files.
