### ISSUE TITLE
allow to specify the expected stderr of the tested script

### ISSUE THREAD

**Issue by soenkehahn** [Originate/check-protocols#87]
It should be possible to capture what the script outputs to `stderr` and compare it to a given expected value.

``` yaml
protocol:
  - foo
  - bar
stderr: expected output
```
