### ISSUE TITLE
don't use multiple yaml documents

### ISSUE THREAD

**Issue by soenkehahn** [Originate/check-protocols#88]
Currently, multiple protocols can be specified by putting them into multiple documents in the same yaml file:

``` yaml
protocol:
  - foo
  - bar
---
protocol:
  - bar
  - baz
```

But for newcomers this seems to be confusing and is maybe generally more an obscure yaml feature? So maybe it'd be better to just switch to:

``` yaml
- protocol:
  - foo
  - bar
- protocol:
  - bar
  - baz
```

The question is whether we then want to disallow specifying a single protocol as a top-level array of steps like this:

``` yaml
- foo
- bar
```

Because that'd be hard to parse and confusing.

cc: @xasopheno
