### ISSUE TITLE
allow to specify an interpreter for a script file

### ISSUE THREAD

**Issue by soenkehahn** [Originate/check-protocols#89]
Currently `check-protocols` can only be run on executables. That means the tested files have to:

- have the executable flag set,
- have a hashbang at the top (or be elf binaries).

It should be possible to get around these restrictions by providing an interpreter, for example like this:

``` yaml
interpreter: python3
tests:
    - arguments: asdff asdfdsakl 
      protocol: 
        - asdfhhhhh
        - aljflkds

    - arguments: fjfjfjf
      protocol:
        - thing1
        - thing2

    - arguments: ofheoheff
      protocol:
        - thing1
```

The current workaround for this is to just make the scripts executable and put the hashbang in, but we don't want to force our users to run their scripts in a certain way.

cc: @xasopheno
