### ISSUE TITLE
support whitelisting certain executables to exclude them from being mocked out

### ISSUE THREAD

**Issue by soenkehahn** [Originate/check-protocols#97]
It should be possible to prevent certain executables from being mocked out. For example `sed`, `awk`, `grep`, `basename` and `jq` should often just be executed during test runs. Here's how this could look like:

``` bash
#!/usr/bin/env bash

ls $(pwd)/$(basename $1)
```

``` yaml
arguments: path/to/file
cwd: /basedir
allowedCommands:
  - basename
protocol:
  - ls /basedir/file
```

Any better ideas than `allowedCommands` for the field name? Maybe `unmock`, `unmocked` or `unmockedCommands`?
